const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const DEFAULT_LOGO='https://raw.githubusercontent.com/elielscarabelliserafim507-lab/Viacao-Motta/main/assets/logo-vm-approved.png';
const state={drivers:JSON.parse(localStorage.getItem('vm_drivers')||'[]'),finance:JSON.parse(localStorage.getItem('vm_finance')||'[]')};
function badgeFromPhone(phone){const digits=(phone||'').replace(/\D/g,'');return digits.length>=4?`MOT-${digits.slice(-4)}`:''}
function getSettings(){return JSON.parse(localStorage.getItem('vm_admin_settings')||'{}')}
function saveSettings(v){localStorage.setItem('vm_admin_settings',JSON.stringify(v));applyTheme()}
function applyTheme(){const s=getSettings();if(s.primary)document.documentElement.style.setProperty('--green',s.primary);if(s.accent){document.documentElement.style.setProperty('--yellow',s.accent);document.documentElement.style.setProperty('--yellow2',s.accent)}if(s.background)document.documentElement.style.setProperty('--bg',s.background);const logo=s.logoUrl||DEFAULT_LOGO;$$('.app-logo').forEach(i=>i.src=logo)}
function renderNotes(){const wrap=$('#adminNotes');if(!state.finance.length){wrap.textContent='Nenhuma nota registrada.';return}wrap.innerHTML=state.finance.slice().reverse().map((x,i)=>{const idx=state.finance.length-1-i;const issues=[];if(!x.value||Number(x.value)<=0)issues.push('Sem valor');if(!x.invoice)issues.push('Sem foto');const st=x.reviewStatus||'pendente';return `<div class="admin-item"><strong>${x.bus||'Viagem'}</strong><div>${Number(x.value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} • ${x.desc||'Sem descrição'}</div><small>${issues.length?'⚠️ '+issues.join(' • '):'Sem alerta automático'}</small><select data-note="${idx}"><option value="pendente" ${st==='pendente'?'selected':''}>Pendente</option><option value="correta" ${st==='correta'?'selected':''}>Nota correta</option><option value="errada" ${st==='errada'?'selected':''}>Nota errada</option><option value="valor_faltando" ${st==='valor_faltando'?'selected':''}>Faltando valor</option><option value="valor_adulterado" ${st==='valor_adulterado'?'selected':''}>Valor adulterado</option><option value="sem_foto" ${st==='sem_foto'?'selected':''}>Sem foto</option></select></div>`}).join('');$$('[data-note]').forEach(sel=>sel.addEventListener('change',()=>{state.finance[Number(sel.dataset.note)].reviewStatus=sel.value;localStorage.setItem('vm_finance',JSON.stringify(state.finance))}))}
function renderDrivers(){const wrap=$('#adminDrivers');if(!state.drivers.length){wrap.textContent='Nenhum motorista cadastrado.';return}wrap.innerHTML=state.drivers.map((d,i)=>`<div class="admin-item"><strong>${d.name}</strong><div>${d.badge||'Sem crachá'} • ${d.email||'Sem e-mail'}</div><small>${d.authorized===false?'⛔ E-mail não autorizado':'✅ E-mail autorizado'}${d.phone?' • '+d.phone:''}</small><button class="logout-btn" style="display:inline-flex;margin-top:8px" data-toggle="${i}">${d.authorized===false?'Autorizar':'Bloquear'} e-mail</button></div>`).join('');$$('[data-toggle]').forEach(btn=>btn.addEventListener('click',()=>{const d=state.drivers[Number(btn.dataset.toggle)];d.authorized=d.authorized===false?true:false;localStorage.setItem('vm_drivers',JSON.stringify(state.drivers));renderDrivers()}))}
const pinStored=localStorage.getItem('vm_admin_pin');$('#gateTitle').textContent=pinStored?'Acesso administrativo':'Configurar acesso';$('#gateText').textContent=pinStored?'Digite seu PIN administrativo para continuar.':'Na primeira entrada, crie um PIN administrativo para este aparelho.';
$('#adminLoginForm').addEventListener('submit',e=>{e.preventDefault();const pin=$('#adminPin').value.trim();if(pin.length<4){$('#adminLoginStatus').textContent='Use pelo menos 4 dígitos.';return}const saved=localStorage.getItem('vm_admin_pin');if(!saved){localStorage.setItem('vm_admin_pin',pin);$('#adminGate').classList.add('hidden')}else if(pin===saved){$('#adminGate').classList.add('hidden')}else{$('#adminLoginStatus').textContent='PIN incorreto.'}});
$('#adminLogout').addEventListener('click',()=>{$('#adminPin').value='';$('#adminGate').classList.remove('hidden')});
$$('.admin-tab').forEach(b=>b.addEventListener('click',()=>{$$('.admin-tab').forEach(x=>x.classList.remove('active'));$$('.admin-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')}));
const settings=getSettings();$('#ruleWrong').checked=!!settings.ruleWrong;$('#ruleMissingValue').checked=settings.ruleMissingValue!==false;$('#ruleAlteredValue').checked=settings.ruleAlteredValue!==false;$('#ruleMissingPhoto').checked=settings.ruleMissingPhoto!==false;$('#logoUrl').value=settings.logoUrl||'';$('#primaryColor').value=settings.primary||'#08752f';$('#accentColor').value=settings.accent||'#ffd21a';$('#backgroundColor').value=settings.background||'#021b0d';
$('#noteRulesForm').addEventListener('submit',e=>{e.preventDefault();const s=getSettings();Object.assign(s,{ruleWrong:$('#ruleWrong').checked,ruleMissingValue:$('#ruleMissingValue').checked,ruleAlteredValue:$('#ruleAlteredValue').checked,ruleMissingPhoto:$('#ruleMissingPhoto').checked});saveSettings(s);alert('Regras de nota salvas.')});
$('#aDriverPhone').addEventListener('input',()=>$('#aDriverBadge').value=badgeFromPhone($('#aDriverPhone').value));
$('#adminDriverForm').addEventListener('submit',e=>{e.preventDefault();const badge=badgeFromPhone($('#aDriverPhone').value);const email=$('#aDriverEmail').value.trim().toLowerCase();if(!badge){$('#accountStatus').textContent='Telefone inválido.';return}if(state.drivers.some(d=>d.badge===badge||String(d.email||'').toLowerCase()===email)){ $('#accountStatus').textContent='Já existe motorista com esse crachá ou e-mail.';return}state.drivers.push({name:$('#aDriverName').value.trim(),phone:$('#aDriverPhone').value.trim(),email,badge,base:$('#aDriverBase').value.trim(),authorized:$('#aDriverAuthorized').checked});localStorage.setItem('vm_drivers',JSON.stringify(state.drivers));e.target.reset();$('#aDriverBadge').value='';$('#aDriverAuthorized').checked=true;$('#accountStatus').textContent='Motorista salvo.';renderDrivers()});
$('#logoForm').addEventListener('submit',e=>{e.preventDefault();const s=getSettings();s.logoUrl=$('#logoUrl').value.trim();saveSettings(s);$('#adminLogoPreview').src=s.logoUrl||DEFAULT_LOGO;alert('Logo salva para este aparelho.')});
$('#themeForm').addEventListener('submit',e=>{e.preventDefault();const s=getSettings();Object.assign(s,{primary:$('#primaryColor').value,accent:$('#accentColor').value,background:$('#backgroundColor').value});saveSettings(s);alert('Cores aplicadas.')});
$('#resetTheme').addEventListener('click',()=>{const s=getSettings();delete s.primary;delete s.accent;delete s.background;saveSettings(s);location.reload()});
renderNotes();renderDrivers();applyTheme();