const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const routes=[
['A-01','Manaus','Belém','Norte'],['A-02','Belém','Manaus','Norte'],['A-03','Manaus','Porto Velho','Norte'],['A-04','Porto Velho','Manaus','Norte'],['A-05','Belém','Macapá','Norte'],['A-06','Macapá','Belém','Norte'],['A-07','Manaus','Boa Vista','Norte'],['A-08','Boa Vista','Manaus','Norte'],['A-09','Rio Branco','Porto Velho','Norte'],['A-10','Porto Velho','Rio Branco','Norte'],['A-11','Palmas','Belém','Norte'],['A-12','Belém','Palmas','Norte'],
['B-01','Salvador','Recife','Nordeste'],['B-02','Recife','Salvador','Nordeste'],['B-03','Fortaleza','Natal','Nordeste'],['B-04','Natal','Fortaleza','Nordeste'],['B-05','Recife','Maceió','Nordeste'],['B-06','Maceió','Recife','Nordeste'],['B-07','Aracaju','Salvador','Nordeste'],['B-08','Salvador','Aracaju','Nordeste'],['B-09','Teresina','Fortaleza','Nordeste'],['B-10','Fortaleza','Teresina','Nordeste'],['B-11','São Luís','Teresina','Nordeste'],['B-12','Teresina','São Luís','Nordeste'],['B-13','João Pessoa','Recife','Nordeste'],['B-14','Recife','João Pessoa','Nordeste'],
['C-01','Brasília','Goiânia','Centro-Oeste'],['C-02','Goiânia','Brasília','Centro-Oeste'],['C-03','Brasília','Cuiabá','Centro-Oeste'],['C-04','Cuiabá','Brasília','Centro-Oeste'],['C-05','Campo Grande','Cuiabá','Centro-Oeste'],['C-06','Cuiabá','Campo Grande','Centro-Oeste'],['C-07','Goiânia','Campo Grande','Centro-Oeste'],['C-08','Campo Grande','Goiânia','Centro-Oeste'],
['D-01','São Paulo','Rio de Janeiro','Sudeste'],['D-02','Rio de Janeiro','São Paulo','Sudeste'],['D-03','São Paulo','Belo Horizonte','Sudeste'],['D-04','Belo Horizonte','São Paulo','Sudeste'],['D-05','Rio de Janeiro','Belo Horizonte','Sudeste'],['D-06','Belo Horizonte','Rio de Janeiro','Sudeste'],['D-07','Vitória','Rio de Janeiro','Sudeste'],['D-08','Rio de Janeiro','Vitória','Sudeste'],['D-09','Vitória','Belo Horizonte','Sudeste'],['D-10','Belo Horizonte','Vitória','Sudeste'],
['E-01','Curitiba','Florianópolis','Sul'],['E-02','Florianópolis','Curitiba','Sul'],['E-03','Florianópolis','Porto Alegre','Sul'],['E-04','Porto Alegre','Florianópolis','Sul'],['E-05','Curitiba','Porto Alegre','Sul'],['E-06','Porto Alegre','Curitiba','Sul'],
['F-01','São Paulo','Brasília','Integração Nacional'],['F-02','Brasília','São Paulo','Integração Nacional'],['F-03','Rio de Janeiro','Salvador','Integração Nacional'],['F-04','Salvador','Rio de Janeiro','Integração Nacional'],['F-05','São Paulo','Curitiba','Integração Nacional'],['F-06','Curitiba','São Paulo','Integração Nacional'],['F-07','Brasília','Salvador','Integração Nacional'],['F-08','Salvador','Brasília','Integração Nacional'],['F-09','São Paulo','Recife','Integração Nacional'],['F-10','Recife','São Paulo','Integração Nacional'],['F-11','Rio de Janeiro','Fortaleza','Integração Nacional'],['F-12','Fortaleza','Rio de Janeiro','Integração Nacional'],['F-13','Manaus','Rio de Janeiro','Integração Nacional'],['F-14','Rio de Janeiro','Manaus','Integração Nacional'],['F-15','Belém','Brasília','Integração Nacional'],['F-16','Brasília','Belém','Integração Nacional'],['F-17','Porto Alegre','São Paulo','Integração Nacional'],['F-18','São Paulo','Porto Alegre','Integração Nacional']
];
const state={drivers:JSON.parse(localStorage.getItem('vm_drivers')||'[]'),trips:JSON.parse(localStorage.getItem('vm_trips')||'[]'),finance:JSON.parse(localStorage.getItem('vm_finance')||'[]')};
let invoiceData='';
function save(){localStorage.setItem('vm_drivers',JSON.stringify(state.drivers));localStorage.setItem('vm_trips',JSON.stringify(state.trips));localStorage.setItem('vm_finance',JSON.stringify(state.finance));render()}
function money(v){return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function badgeFromPhone(phone){const digits=(phone||'').replace(/\D/g,'');return digits.length>=4?`MOT-${digits.slice(-4)}`:''}
function normalizeEmail(email){return (email||'').trim().toLowerCase()}
function initRoutes(){const select=$('#tripRoute');select.innerHTML=routes.map(r=>`<option value="${r[0]} • ${r[1]} → ${r[2]}">${r[0]} • ${r[1]} → ${r[2]}</option>`).join('');$('#routeCards').innerHTML=routes.map(r=>`<article class="route-card"><strong>${r[0]}</strong><h3>${r[1]} → ${r[2]}</h3><span>${r[3]}</span></article>`).join('');$('#featuredRoutes').innerHTML=routes.slice(0,6).map(r=>`<div><strong>${r[0]}</strong><span>${r[1]} → ${r[2]}</span></div>`).join('');$('#statRoutes').textContent=routes.length}
function render(){const d=$('#driversList');d.innerHTML=state.drivers.length?state.drivers.map(x=>`<div><strong>${x.name}</strong><span>Crachá ${x.badge}${x.email?` • ${x.email}`:''}${x.base?` • ${x.base}`:''}</span></div>`).join(''):'Nenhum motorista cadastrado.';d.classList.toggle('empty',!state.drivers.length);const t=$('#tripsList');t.innerHTML=state.trips.length?state.trips.map(x=>`<div><strong>${x.route}</strong><span>${x.driver} • ${x.date} ${x.time}</span></div>`).join(''):'Nenhuma viagem cadastrada.';t.classList.toggle('empty',!state.trips.length);const n=$('#nextTrips');n.innerHTML=state.trips.length?state.trips.slice(-4).reverse().map(x=>`<div><strong>${x.route}</strong><span>${x.driver} • ${x.date} ${x.time}</span></div>`).join(''):'Nenhuma viagem cadastrada.';n.classList.toggle('empty',!state.trips.length);const f=$('#financeList');f.innerHTML=state.finance.length?state.finance.slice().reverse().map(x=>`<div class="finance-item"><div><strong>${x.bus}</strong><span>${money(x.value)}</span><span>${x.desc}</span><small>${x.badge||x.email||'Sem identificação'}</small></div>${x.invoice?`<img src="${x.invoice}" alt="Nota fiscal">`:''}</div>`).join(''):'Nenhuma nota registrada.';f.classList.toggle('empty',!state.finance.length);const total=state.finance.reduce((a,x)=>a+Number(x.value||0),0);$('#statDrivers').textContent=state.drivers.length;$('#statTrips').textContent=state.trips.length;$('#statBalance').textContent=money(total)}
function showApp(){const label=sessionStorage.getItem('vm_session_label')||sessionStorage.getItem('vm_session_badge')||sessionStorage.getItem('vm_session_email')||'';$('#loginGate').classList.add('hidden');$('#loggedBadge').textContent=label;$('#logoutBtn').style.display=label?'inline-flex':'none'}
function showLogin(){sessionStorage.removeItem('vm_session_badge');sessionStorage.removeItem('vm_session_email');sessionStorage.removeItem('vm_session_label');$('#loginGate').classList.remove('hidden');$('#loggedBadge').textContent='';$('#logoutBtn').style.display='none'}
$$('.nav').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+btn.dataset.target).classList.add('active');$('#sidebar').classList.remove('open')}));
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#driverPhone').addEventListener('input',()=>{$('#driverBadge').value=badgeFromPhone($('#driverPhone').value)});
$('#driverForm').addEventListener('submit',e=>{e.preventDefault();const badge=badgeFromPhone($('#driverPhone').value);const email=normalizeEmail($('#driverEmail').value);if(!badge){alert('Informe um telefone válido.');return}if(!email){alert('Informe o e-mail do motorista.');return}if(state.drivers.some(d=>d.badge===badge)){alert('Este crachá já está cadastrado.');return}if(state.drivers.some(d=>normalizeEmail(d.email)===email)){alert('Este e-mail já está cadastrado.');return}state.drivers.push({name:$('#driverName').value.trim(),phone:$('#driverPhone').value.trim(),email,badge,base:$('#driverBase').value.trim()});e.target.reset();$('#driverBadge').value='';save()});
$('#tripForm').addEventListener('submit',e=>{e.preventDefault();state.trips.push({route:$('#tripRoute').value,driver:$('#tripDriver').value.trim(),date:$('#tripDate').value,time:$('#tripTime').value});e.target.reset();save()});
$('#financeInvoice').addEventListener('change',e=>{const file=e.target.files[0];invoiceData='';$('#invoiceFileName').textContent=file?file.name:'Tire uma foto ou escolha uma imagem da nota.';if(!file){$('#invoicePreviewWrap').hidden=true;return}const reader=new FileReader();reader.onload=()=>{invoiceData=reader.result;$('#invoicePreview').src=invoiceData;$('#invoicePreviewWrap').hidden=false};reader.readAsDataURL(file)});
$('#financeForm').addEventListener('submit',e=>{e.preventDefault();if(!invoiceData){alert('Envie uma foto da nota fiscal.');return}state.finance.push({bus:$('#financeBus').value,desc:$('#financeDesc').value.trim(),value:Number($('#financeValue').value),invoice:invoiceData,badge:sessionStorage.getItem('vm_session_badge')||'',email:sessionStorage.getItem('vm_session_email')||''});e.target.reset();invoiceData='';$('#invoicePreviewWrap').hidden=true;$('#invoiceFileName').textContent='Tire uma foto ou escolha uma imagem da nota.';save()});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const raw=$('#loginIdentity').value.trim();const badge=raw.toUpperCase();const email=normalizeEmail(raw);let driver=null;if(/^MOT-\d{4}$/.test(badge)){driver=state.drivers.find(d=>d.badge===badge)||null}else if(email.includes('@')){driver=state.drivers.find(d=>normalizeEmail(d.email)===email)||null}else{$('#loginStatus').textContent='Digite um crachá no formato MOT-0000 ou um e-mail válido.';return}if(state.drivers.length&& !driver){$('#loginStatus').textContent='Crachá ou e-mail não encontrado neste aparelho.';return}if(driver){sessionStorage.setItem('vm_session_badge',driver.badge||'');sessionStorage.setItem('vm_session_email',driver.email||'');sessionStorage.setItem('vm_session_label',driver.badge||driver.email||driver.name)}else{sessionStorage.setItem('vm_session_label',/^MOT-\d{4}$/.test(badge)?badge:email);if(/^MOT-\d{4}$/.test(badge))sessionStorage.setItem('vm_session_badge',badge);else sessionStorage.setItem('vm_session_email',email)}$('#loginStatus').textContent='';showApp()});
$('#logoutBtn').addEventListener('click',showLogin);
$('#skinForm').addEventListener('submit',e=>{e.preventDefault();$('#skinStatus').textContent=`Pedido registrado para ${$('#skinBus').value}.`;e.target.reset()});
$('#aiForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#aiInput');const text=input.value.trim();if(!text)return;const wrap=$('#aiMessages');wrap.insertAdjacentHTML('beforeend',`<div class="ai-msg" style="align-self:flex-end;background:#1f6feb">${text.replace(/[<>]/g,'')}</div>`);wrap.insertAdjacentHTML('beforeend','<div class="ai-msg">Esta primeira versão ainda não está conectada a uma IA real.</div>');input.value='';wrap.scrollTop=wrap.scrollHeight});
initRoutes();render();(sessionStorage.getItem('vm_session_label')||sessionStorage.getItem('vm_session_badge')||sessionStorage.getItem('vm_session_email'))?showApp():showLogin();