const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const routes=[
['A-01','Manaus','Belém','Norte'],['A-02','Belém','Manaus','Norte'],['A-03','Manaus','Porto Velho','Norte'],['A-04','Porto Velho','Manaus','Norte'],['A-05','Belém','Macapá','Norte'],['A-06','Macapá','Belém','Norte'],['A-07','Manaus','Boa Vista','Norte'],['A-08','Boa Vista','Manaus','Norte'],['A-09','Rio Branco','Porto Velho','Norte'],['A-10','Porto Velho','Rio Branco','Norte'],['A-11','Palmas','Belém','Norte'],['A-12','Belém','Palmas','Norte'],
['B-01','Salvador','Recife','Nordeste'],['B-02','Recife','Salvador','Nordeste'],['B-03','Fortaleza','Natal','Nordeste'],['B-04','Natal','Fortaleza','Nordeste'],['B-05','Recife','Maceió','Nordeste'],['B-06','Maceió','Recife','Nordeste'],['B-07','Aracaju','Salvador','Nordeste'],['B-08','Salvador','Aracaju','Nordeste'],['B-09','Teresina','Fortaleza','Nordeste'],['B-10','Fortaleza','Teresina','Nordeste'],['B-11','São Luís','Teresina','Nordeste'],['B-12','Teresina','São Luís','Nordeste'],['B-13','João Pessoa','Recife','Nordeste'],['B-14','Recife','João Pessoa','Nordeste'],
['C-01','Brasília','Goiânia','Centro-Oeste'],['C-02','Goiânia','Brasília','Centro-Oeste'],['C-03','Brasília','Cuiabá','Centro-Oeste'],['C-04','Cuiabá','Brasília','Centro-Oeste'],['C-05','Campo Grande','Cuiabá','Centro-Oeste'],['C-06','Cuiabá','Campo Grande','Centro-Oeste'],['C-07','Goiânia','Campo Grande','Centro-Oeste'],['C-08','Campo Grande','Goiânia','Centro-Oeste'],
['D-01','São Paulo','Rio de Janeiro','Sudeste'],['D-02','Rio de Janeiro','São Paulo','Sudeste'],['D-03','São Paulo','Belo Horizonte','Sudeste'],['D-04','Belo Horizonte','São Paulo','Sudeste'],['D-05','Rio de Janeiro','Belo Horizonte','Sudeste'],['D-06','Belo Horizonte','Rio de Janeiro','Sudeste'],['D-07','Vitória','Rio de Janeiro','Sudeste'],['D-08','Rio de Janeiro','Vitória','Sudeste'],['D-09','Vitória','Belo Horizonte','Sudeste'],['D-10','Belo Horizonte','Vitória','Sudeste'],
['E-01','Curitiba','Florianópolis','Sul'],['E-02','Florianópolis','Curitiba','Sul'],['E-03','Florianópolis','Porto Alegre','Sul'],['E-04','Porto Alegre','Florianópolis','Sul'],['E-05','Curitiba','Porto Alegre','Sul'],['E-06','Porto Alegre','Curitiba','Sul'],
['F-01','São Paulo','Brasília','Integração Nacional'],['F-02','Brasília','São Paulo','Integração Nacional'],['F-03','Rio de Janeiro','Salvador','Integração Nacional'],['F-04','Salvador','Rio de Janeiro','Integração Nacional'],['F-05','São Paulo','Curitiba','Integração Nacional'],['F-06','Curitiba','São Paulo','Integração Nacional'],['F-07','Brasília','Salvador','Integração Nacional'],['F-08','Salvador','Brasília','Integração Nacional'],['F-09','São Paulo','Recife','Integração Nacional'],['F-10','Recife','São Paulo','Integração Nacional'],['F-11','Rio de Janeiro','Fortaleza','Integração Nacional'],['F-12','Fortaleza','Rio de Janeiro','Integração Nacional'],['F-13','Manaus','Rio de Janeiro','Integração Nacional'],['F-14','Rio de Janeiro','Manaus','Integração Nacional'],['F-15','Belém','Brasília','Integração Nacional'],['F-16','Brasília','Belém','Integração Nacional'],['F-17','Porto Alegre','São Paulo','Integração Nacional'],['F-18','São Paulo','Porto Alegre','Integração Nacional']
];
const state={drivers:JSON.parse(localStorage.getItem('vm_drivers')||'[]'),trips:JSON.parse(localStorage.getItem('vm_trips')||'[]'),finance:JSON.parse(localStorage.getItem('vm_finance')||'[]')};
function save(){localStorage.setItem('vm_drivers',JSON.stringify(state.drivers));localStorage.setItem('vm_trips',JSON.stringify(state.trips));localStorage.setItem('vm_finance',JSON.stringify(state.finance));render()}
function money(v){return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function initRoutes(){const select=$('#tripRoute');select.innerHTML=routes.map(r=>`<option value="${r[0]} • ${r[1]} → ${r[2]}">${r[0]} • ${r[1]} → ${r[2]}</option>`).join('');$('#routeCards').innerHTML=routes.map(r=>`<article class="route-card"><strong>${r[0]}</strong><h3>${r[1]} → ${r[2]}</h3><span>${r[3]}</span></article>`).join('');$('#featuredRoutes').innerHTML=routes.slice(0,6).map(r=>`<div><strong>${r[0]}</strong><span>${r[1]} → ${r[2]}</span></div>`).join('');$('#statRoutes').textContent=routes.length}
function render(){const d=$('#driversList');d.innerHTML=state.drivers.length?state.drivers.map(x=>`<div><strong>${x.name}</strong><span>Crachá ${x.badge}${x.base?` • ${x.base}`:''}</span></div>`).join(''):'Nenhum motorista cadastrado.';d.classList.toggle('empty',!state.drivers.length);const t=$('#tripsList');t.innerHTML=state.trips.length?state.trips.map(x=>`<div><strong>${x.route}</strong><span>${x.driver} • ${x.date} ${x.time}</span></div>`).join(''):'Nenhuma viagem cadastrada.';t.classList.toggle('empty',!state.trips.length);const n=$('#nextTrips');n.innerHTML=state.trips.length?state.trips.slice(-4).reverse().map(x=>`<div><strong>${x.route}</strong><span>${x.driver} • ${x.date} ${x.time}</span></div>`).join(''):'Nenhuma viagem cadastrada.';n.classList.toggle('empty',!state.trips.length);const f=$('#financeList');f.innerHTML=state.finance.length?state.finance.slice().reverse().map(x=>`<div><strong>${x.desc}</strong><span>${x.type==='entrada'?'+':'-'} ${money(x.value)}</span></div>`).join(''):'Nenhuma movimentação.';f.classList.toggle('empty',!state.finance.length);const balance=state.finance.reduce((a,x)=>a+(x.type==='entrada'?Number(x.value):-Number(x.value)),0);$('#statDrivers').textContent=state.drivers.length;$('#statTrips').textContent=state.trips.length;$('#statBalance').textContent=money(balance)}
$$('.nav').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+btn.dataset.target).classList.add('active');$('#sidebar').classList.remove('open')}));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#driverForm').addEventListener('submit',e=>{e.preventDefault();state.drivers.push({name:$('#driverName').value.trim(),badge:$('#driverBadge').value.trim(),base:$('#driverBase').value.trim()});e.target.reset();save()});$('#tripForm').addEventListener('submit',e=>{e.preventDefault();state.trips.push({route:$('#tripRoute').value,driver:$('#tripDriver').value.trim(),date:$('#tripDate').value,time:$('#tripTime').value});e.target.reset();save()});$('#financeForm').addEventListener('submit',e=>{e.preventDefault();state.finance.push({type:$('#financeType').value,desc:$('#financeDesc').value.trim(),value:Number($('#financeValue').value)});e.target.reset();save()});$('#skinForm').addEventListener('submit',e=>{e.preventDefault();$('#skinStatus').textContent=`Pedido registrado para ${$('#skinBus').value}.`;e.target.reset()});$('#aiForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#aiInput');const text=input.value.trim();if(!text)return;const wrap=$('#aiMessages');wrap.insertAdjacentHTML('beforeend',`<div class="ai-msg" style="align-self:flex-end;background:#1f6feb">${text.replace(/[<>]/g,'')}</div>`);wrap.insertAdjacentHTML('beforeend','<div class="ai-msg">Esta primeira versão ainda não está conectada a uma IA real. Posso virar um assistente conectado em uma próxima etapa.</div>');input.value='';wrap.scrollTop=wrap.scrollHeight});initRoutes();render();